### Indexing - same concept as python list

In [1]:
import numpy as np

#### 1-dimensional vector indexing

In [3]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
x[4]

4

#### 2-dim indexing

In [13]:
x = np.arange(10).reshape(2,5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [21]:
x[1, 2]

7

In [22]:
x[0]

array([0, 1, 2, 3, 4])

#### 3-dimensional indexing

In [23]:
x = np.arange(36).reshape(3,4,3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [24]:
x[1,2, 1]

19

#### slicing - used same concept as list, string 

#### 1dim vector slicing

In [25]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [26]:
x[1:7]

array([1, 2, 3, 4, 5, 6])

#### 2dim slicing

In [33]:
x = np.arange(10).reshape(2,5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [34]:
x[0, :2]

array([0, 1])

In [35]:
x[:1, :2]

array([[0, 1]])

#### 3dim slicing

In [39]:
x = np.arange(54).reshape(3,6,3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]
  [48 49 50]
  [51 52 53]]]


In [44]:
x[:1, :2, :]

array([[[0, 1, 2],
        [3, 4, 5]]])

In [45]:
x[0, :2, :]

array([[0, 1, 2],
       [3, 4, 5]])