In [1]:
import numpy as np

### numpy docu

In [2]:
x = np.arange(15).reshape(3,5)
y = np.random.rand(15).reshape(3,5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.04061612 0.25428166 0.69270102 0.51654709 0.0237266 ]
 [0.30213479 0.88340776 0.2765685  0.36923532 0.6802922 ]
 [0.35396363 0.07919597 0.91241423 0.69956158 0.52011514]]


### arithmetic function - add, substract, multiply, divide
 - the shape must be same

In [3]:
np.add(x,y)

array([[ 0.04061612,  1.25428166,  2.69270102,  3.51654709,  4.0237266 ],
       [ 5.30213479,  6.88340776,  7.2765685 ,  8.36923532,  9.6802922 ],
       [10.35396363, 11.07919597, 12.91241423, 13.69956158, 14.52011514]])

In [4]:
np.subtract(x,y)

array([[-0.04061612,  0.74571834,  1.30729898,  2.48345291,  3.9762734 ],
       [ 4.69786521,  5.11659224,  6.7234315 ,  7.63076468,  8.3197078 ],
       [ 9.64603637, 10.92080403, 11.08758577, 12.30043842, 13.47988486]])

In [5]:
x + y 


array([[ 0.04061612,  1.25428166,  2.69270102,  3.51654709,  4.0237266 ],
       [ 5.30213479,  6.88340776,  7.2765685 ,  8.36923532,  9.6802922 ],
       [10.35396363, 11.07919597, 12.91241423, 13.69956158, 14.52011514]])

In [6]:
x- y

array([[-0.04061612,  0.74571834,  1.30729898,  2.48345291,  3.9762734 ],
       [ 4.69786521,  5.11659224,  6.7234315 ,  7.63076468,  8.3197078 ],
       [ 9.64603637, 10.92080403, 11.08758577, 12.30043842, 13.47988486]])

In [7]:
x / y

array([[  0.        ,   3.93264692,   2.88724855,   5.80779577,
        168.58714834],
       [ 16.54890515,   6.79188053,  25.31018576,  21.66639947,
         13.22960924],
       [ 28.25148993, 138.89595912,  13.15192113,  18.58306738,
         26.91711697]])

### statistics operation - avg, median, mean, max, min

In [8]:
print(y)

[[0.04061612 0.25428166 0.69270102 0.51654709 0.0237266 ]
 [0.30213479 0.88340776 0.2765685  0.36923532 0.6802922 ]
 [0.35396363 0.07919597 0.91241423 0.69956158 0.52011514]]


In [9]:
np.mean(y)

0.44031744086752705

In [10]:
y.mean()

0.44031744086752705

In [11]:
np.max(y)

0.9124142305804084

In [12]:
np.argmax(y) # returns the index of max num

12

In [13]:
np.var(y), np.median(y), np.std(y)

(0.07844138918766536, 0.36923532267299486, 0.2800738995116563)

### aggregation function - sum, cumsum 

In [14]:
y

array([[0.04061612, 0.25428166, 0.69270102, 0.51654709, 0.0237266 ],
       [0.30213479, 0.88340776, 0.2765685 , 0.36923532, 0.6802922 ],
       [0.35396363, 0.07919597, 0.91241423, 0.69956158, 0.52011514]])

In [15]:
np.sum(y)

6.604761613012906

In [19]:
np.sum(y, axis=0)

array([0.69671454, 1.2168854 , 1.88168374, 1.58534399, 1.22413394])

In [16]:
np.cumsum(y)

array([0.04061612, 0.29489778, 0.9875988 , 1.50414589, 1.52787249,
       1.83000728, 2.71341504, 2.98998354, 3.35921886, 4.03951106,
       4.3934747 , 4.47267066, 5.38508489, 6.08464648, 6.60476161])

### any, all 

In [20]:
z = np.random.randn(10)
print(z)

[ 0.22345122  0.30008044  0.95678076  0.0846498   0.35212712 -0.46133386
  0.15865372 -0.61961485 -0.84065587 -0.23592735]


In [23]:
np.any(z > 10)

False

In [24]:
np.all(z > 0)

False

### where

In [25]:
z = np.random.randn(10)
print(z)

[ 1.46034197  0.43987789 -0.26064272 -0.84957787  0.45057003  2.41683519
 -0.58807803 -1.15331665  0.42404356  1.14822333]


In [26]:
np.where(z > 0, z, 0)

array([1.46034197, 0.43987789, 0.        , 0.        , 0.45057003,
       2.41683519, 0.        , 0.        , 0.42404356, 1.14822333])