### axis 
- some functions have axis keyword parameter

In [2]:
import numpy as np
x = np.arange(15)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [3]:
np.sum(x)

105

In [4]:
np.sum(x, axis=0)

105

In [7]:
y = x.reshape(3,5)
print(y)

np.sum(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


105

In [8]:
np.sum(y, axis=0) #  0 = col-direction 

array([15, 18, 21, 24, 27])

In [10]:
np.sum(y, axis=1) # 1 = raw-direction

array([10, 35, 60])

In [12]:
z = np.arange(36).reshape(3,4,3)
print(z)

np.sum(z, axis=0)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


array([[36, 39, 42],
       [45, 48, 51],
       [54, 57, 60],
       [63, 66, 69]])

In [13]:
np.sum(z, axis=1) # col

array([[ 18,  22,  26],
       [ 66,  70,  74],
       [114, 118, 122]])

In [14]:
np.sum(z, axis=2) # row 

array([[  3,  12,  21,  30],
       [ 39,  48,  57,  66],
       [ 75,  84,  93, 102]])

In [15]:
np.sum(z, axis=-1)

array([[  3,  12,  21,  30],
       [ 39,  48,  57,  66],
       [ 75,  84,  93, 102]])

In [17]:
# when axis is a tuple
print(z)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [19]:
np.sum(z, axis=(0,2))

array([117, 144, 171, 198])