In [1]:
import numpy as np

### when shape is same

In [4]:
x = np.arange(15).reshape(3,5)
y = np.random.rand(15).reshape(3,5)
print(x)
print(y)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.5740243  0.74027346 0.35093003 0.32694152 0.94128151]
 [0.18515606 0.02188548 0.21968521 0.63170254 0.49196667]
 [0.63485058 0.44280049 0.29959825 0.2246189  0.02282701]]


In [5]:
x + y

array([[ 0.5740243 ,  1.74027346,  2.35093003,  3.32694152,  4.94128151],
       [ 5.18515606,  6.02188548,  7.21968521,  8.63170254,  9.49196667],
       [10.63485058, 11.44280049, 12.29959825, 13.2246189 , 14.02282701]])

- scalar operation

In [6]:
x + 2

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [7]:
x * 2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

### when shape is diffenrent

In [19]:
a = np.arange(12).reshape(4,3)
b = np.arange(100,103)
c = np.arange(1000,1004)
d = b.reshape(1,3)

print('a: ',a)
print('b: ',b)
print('c: ',c)
print('d: ',d)

a:  [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
b:  [100 101 102]
c:  [1000 1001 1002 1003]
d:  [[100 101 102]]


In [12]:
a + b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [13]:
a + c # this cannot be done since the row num is not same vector as d 

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [20]:
a + d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])