### operate linear algebra using linalg module

In [1]:
import numpy as np

### np.linalg.inv
- To find inverse matrix

In [2]:
x = np.random.rand(3, 3)
print(x)

np.linalg.inv(x)

[[0.73299206 0.7031529  0.77940233]
 [0.80289273 0.05579181 0.19462089]
 [0.38911469 0.40247044 0.55929833]]


array([[ 0.75871111,  1.28133272, -1.50316079],
       [ 6.01056328, -1.71761879, -7.77825045],
       [-4.85304451,  0.34454852,  8.4309528 ]])

In [3]:
x @ np.linalg.inv(x)

array([[ 1.00000000e+00, -6.45303856e-17, -1.06788892e-15],
       [ 1.61152922e-17,  1.00000000e+00,  1.46153618e-17],
       [ 1.30098539e-16, -2.72746922e-17,  1.00000000e+00]])

In [4]:
np.matmul(x, np.linalg.inv(x))

array([[ 1.00000000e+00, -6.45303856e-17, -1.06788892e-15],
       [ 1.61152922e-17,  1.00000000e+00,  1.46153618e-17],
       [ 1.30098539e-16, -2.72746922e-17,  1.00000000e+00]])

### np.linalg.solve
- Ax = B shape linear algebra 


In [6]:
A = np.array([[1,1], [2,4]])
B = np.array([25,64])

x = np.linalg.solve(A,B)
print(x)

np.allclose(A@x, B)

[18.  7.]


True