### boolean indexing 
- when ndarray indexing, returns the boolian list and filters the true only.
- using broadcasting. get the bool list from ndarray

In [1]:
import numpy as np

In [2]:
x = np.random.randint(1,100,size=10)
print(x)

[ 4 85 78 69 99  9 67 91 96 50]


In [6]:
even_mask = x % 2 == 0
print(even_mask)

[ True False  True False False False False False  True  True]


- returns the boolean list by a index number

In [5]:
x[even_mask]

array([ 4, 78, 96, 50])

In [7]:
x[x % 2 == 0]

array([ 4, 78, 96, 50])

In [9]:
x[x > 30]

array([85, 78, 69, 99, 67, 91, 96, 50])

### using multiple statement

In [14]:
x % 2 == 0
x < 30

x[(x % 2 == 0) & (x < 30)] # only brings the even number and less than 30

array([4])

In [15]:
x < 30
x > 50

x[(x < 30) | (x > 50)]

array([ 4, 85, 78, 69, 99,  9, 67, 91, 96])

### ex) 2019, July Seoul avg wheather data
- find num of above 25C days 
- find avg num of above 25C

In [16]:
temp = np.array(
[23.9, 24.4, 24.1, 25.4, 27.6, 29.7,
 26.7, 25.1, 25.0, 22.7, 21.9, 23.6, 
 24.9, 25.9, 23.8, 24.7, 25.6, 26.9, 
 28.6, 28.0, 25.1, 26.7, 28.1, 26.5,
 26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8   
])

In [17]:
len(temp)

31

In [18]:
temp > 25.0

array([False, False, False,  True,  True,  True,  True,  True, False,
       False, False, False, False,  True, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [21]:
len(temp[temp > 25.0]) # num of above 25 degree

21

In [22]:
np.sum(temp > 25.0)

21

In [27]:
temp[temp > 25.0]

array([25.4, 27.6, 29.7, 26.7, 25.1, 25.9, 25.6, 26.9, 28.6, 28. , 25.1,
       26.7, 28.1, 26.5, 26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

In [25]:
np.mean(temp[temp > 25.0])

26.857142857142858